name: Demo

on:
    pull_request:
        branches:
            - origin/main
            
jobs:
    test:
        runs-on: ubuntu-latest
        container:
            image: node:latest  # ✅ Use a valid Node.js Docker image
        steps:
            - uses: actions/checkout@v3  # ✅ No node-version here
            
            - uses: actions/setup-node@v3  # ✅ Correct place to set node version
              with:
                node-version: latest
            
            - run: yarn install
            - run: yarn test

    build:
        runs-on: ubuntu-latest
        container:
            image: node:latest  # ✅ Use a valid Node.js Docker image
        steps:
            - uses: actions/checkout@v3  # ✅ No node-version here
            
            - uses: actions/setup-node@v3  # ✅ Correct place to set node version
              with:
                node-version: latest
            
            - run: yarn install         
            - run: yarn build
